# Generated by Django 3.2.18 on 2023-04-29 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('url', models.TextField()),
                ('visitas', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('tags', models.TextField()),
                ('descricao', models.TextField()),
                ('isLiked', models.BooleanField()),
                ('isFav', models.BooleanField()),
            ],
            options={
                'db_table': 'painel',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imgs/')),
                ('painel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.painel')),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
